pipeline:
- name: nlp_spacy
- name: tokenizer_spacy
- name: intent_featurizer_spacy
- name: ner_crf
- name: ner_spacy
- name: intent_classifier_sklearn
- name: ner_duckling_http
  url: "http://localhost:8000"
  dimensions:
  - number
  - email
  - amount-of-money
language: en
